# Per environment values which override defaults in hmpps-digital-prison-reporting-mi-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: digital-prison-reporting-mi-ui-dev.hmpps.service.justice.gov.uk
    modsecurity_enabled: false

  env:
    ENVIRONMENT_NAME: "development"
    INGRESS_URL: 'https://digital-prison-reporting-mi-ui-dev.hmpps.service.justice.gov.uk'
    HMPPS_AUTH_URL: 'https://sign-in-dev.hmpps.service.justice.gov.uk/auth'
    HMPPS_MANAGE_USERS_URL: 'https://manage-users-api-dev.hmpps.service.justice.gov.uk'
    TOKEN_VERIFICATION_API_URL: 'https://token-verification-api-dev.prison.service.justice.gov.uk'
    REPORTING_API_URL: 'http://hmpps-digital-prison-reporting-mi-dev.hmpps-digital-prison-reporting-mi-dev.svc.cluster.local'
    TOKEN_VERIFICATION_ENABLED: true
    DEFINITION_PATHS_ENABLED: true
    DPS_COMPONENT_API_URL: 'https://frontend-components-dev.hmpps.service.justice.gov.uk'
    DPS_URL: 'https://dps-dev.prison.service.justice.gov.uk'
    ACTIVE_ESTABLISHMENTS: '***'

  allowlist:
    groups:
      - circleci
      - internal
      - prisons
      - private_prisons

generic-prometheus-alerts:
  alertSeverity: digital-prison-reporting-dev
