name: Bump library version

on:
  workflow_dispatch:

jobs:
  bump-version:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: 24.x

      - name: SLSA - supply chain attack mitigation
        uses: ministryofjustice/devsecops-actions/sca/slsa@877a6683738d4643f16c2c306e908bb5ef5487c2
        with:
          security-patch-package-exclusion: "@ministryofjustice/hmpps-digital-prison-reporting-frontend"

      - name: Get version
        id: get-version
        run: |
          CURRENT_VERSION=$(npm view @ministryofjustice/hmpps-digital-prison-reporting-frontend version)
          echo "Current version: $CURRENT_VERSION"
          echo "current_version=$CURRENT_VERSION" >> "$GITHUB_OUTPUT"

      - name: Find and replace library version
        run: >-
          perl -pi -e 's|"\@ministryofjustice\/hmpps-digital-prison-reporting-frontend": "\d+\.\d+\.\d+.,|"\@ministryofjustice/hmpps-digital-prison-reporting-frontend": "^${{ steps.get-version.outputs.current_version }}",|' package.json

      - name: Update package lock
        run: npm install

      - name: Commit version bump
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git checkout -b feature/bump-lib-to-v${{ steps.get-version.outputs.current_version }}
          git add package.json package-lock.json
          git commit -m "Bump library version to ${{ steps.get-version.outputs.current_version }}"
          git push origin feature/bump-lib-to-v${{ steps.get-version.outputs.current_version }}
          git tag -a Lib-v${{ steps.get-version.outputs.current_version }} -m Lib-v${{ steps.get-version.outputs.current_version }}
          git push origin Lib-v${{ steps.get-version.outputs.current_version }}

      - name: Create pull request
        run: gh pr create -B main -H 'feature/bump-lib-to-v${{ steps.get-version.outputs.current_version }}' --title 'Bump library version to ${{ steps.get-version.outputs.current_version }}' --body ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
