name: PR preparation

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  preparation:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
        with:
          node-version: 24.x

      - name: SLSA - supply chain attack mitigation
        uses: ministryofjustice/devsecops-actions/sca/slsa@e3c63a5986ea6e7d57d38b7f72e5b8cf08dc7020
        with:
          security-patch-package-exclusion: "@ministryofjustice/hmpps-digital-prison-reporting-frontend"

      - run: npm run setup --no-audit

      - name: Add linting fixes
        run: npm run lint

      - name: Calculate test coverage
        run: |
          npm run test > logs.txt
          gh pr comment ${{ github.event.pull_request.number }} --body "$(grep '% Stmts' logs.txt -A2)"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
