name: PR preparation

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  preparation:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version: 24.x

      - name: SLSA - supply chain attack mitigation
        uses: ministryofjustice/devsecops-actions/sca/slsa@7dc13c20e2bf541b8a77fa1320a04983b18846f6
        with:
          security-patch-package-exclusion: '@ministryofjustice/hmpps-digital-prison-reporting-frontend'

      - run: npm run setup --no-audit

      - name: Setup Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97
        with:
          python-version: '3.x'

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit checks
        run: pre-commit run --all-files

      - name: Calculate test coverage
        run: |
          npm run test > logs.txt
          gh pr comment ${{ github.event.pull_request.number }} --body "$(grep '% Stmts' logs.txt -A2)"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
