name: PR preparation

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  preparation:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version: 24.x

      - name: SLSA - supply chain attack mitigation
        uses: ministryofjustice/devsecops-actions/sca/slsa@7dc13c20e2bf541b8a77fa1320a04983b18846f6
        with:
          security-patch-package-exclusion: "@ministryofjustice/hmpps-digital-prison-reporting-frontend"

      - run: npm run setup --no-audit

      - name: Setup Python
        uses: actions/setup-python@c8813ba1bc76ebf779b911ad8ffccbf2e449cb48
        with:
          python-version: '3.x'

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit checks
        run: pre-commit run --all-files

      - name: Calculate test coverage
        run: |
          npm run test > logs.txt
          gh pr comment ${{ github.event.pull_request.number }} --body "$(grep '% Stmts' logs.txt -A2)"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
