name: Security SCA actions scan

on:
  schedule:
    - cron: '19 6 * * MON-FRI' # Every weekday
  pull_request:
    branches: ['**']
  workflow_dispatch:

permissions: {}

jobs:
  sca:
    name: Software Composition Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 30

    permissions:
      contents: write
      pull-requests: write
      issues: write
      security-events: read

    steps:
      - name: Run SCA
        uses: ministryofjustice/devsecops-actions/sca@7dc13c20e2bf541b8a77fa1320a04983b18846f6 # v1.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          renovate: 'false'
      - name: SCA slack notification
        uses: ministryofjustice/hmpps-github-shared-actions/.github/actions/slack_codescan_notification@fddc5f11d6a8ce9b82a06fe76268835bfd99bcd4 # v1
        if: failure() && github.event_name == 'schedule' && github.ref == 'refs/heads/main'
        with:
          title: 'Software Composition Analysis Actions Scan'
          warningOnly: false
          channel_id: ${{ vars.SECURITY_ALERTS_SLACK_CHANNEL_ID || 'NO_SLACK' }}
          SLACK_BOT_TOKEN: ${{ secrets.HMPPS_SRE_SLACK_BOT_TOKEN }}
